import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Map Generator";

    width: 800px;
    height: 600px;

    in property <image> map;

    callback request-new-map();

    VerticalLayout {
        width: parent.width;
        height: parent.height;

        spacing: 10px;
        padding: 10px;

        alignment: end;
        
        Image {
            source: root.map;
        }

        Button {
            text: "Generate map";
            
            clicked => {
                root.request-new-map();
            }
        }
    }
}
