import { Button, VerticalBox, Slider, ComboBox, SpinBox, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Map Generator";

    max-width: 80rem;
    min-height: 45rem;

    in property <image> map;

    property <int> cols;
    property <int> rows;
    property <string> style_code;

    callback request-new-map(int, int, string);
    callback request-save-map();

    public function enable_generate_button() {
        gen_button.text = "Generate map";
        gen_button.enabled = true;
    }

    public function enable_save_button() {
        save_button.text = "Save map";
        save_button.enabled = true;
    }

    HorizontalBox {
        width: parent.width;
        height: parent.height;

        spacing: 1rem;
        padding: 0.5rem;

        alignment: space-between;

        VerticalBox {
            VerticalBox {
                alignment: start;
                min-width: 20rem;
                spacing: 0.5rem;

                col_box := SpinBox {
                    minimum: 12;
                    horizontal-stretch: 0;
                    maximum: 64;

                    value: 32;
                    vertical-stretch: 0;
                    visible: true;

                    init() => {
                        root.cols = self.value;
                    }

                    edited(value) => {
                        root.cols = value;
                    }
                }

                row_box := SpinBox {
                    minimum: 12;
                    maximum: 64;

                    value: 24;

                    init() => {
                        root.rows = self.value;
                    }

                    edited(value) => {
                        root.rows = value;
                    }
                }

                style_selector := ComboBox {
                    model: [
                        "Symphony of the Night",
                        "Aria of Sorrow",
                        "Circle of the Moon",
                        "Harmony of Dissonance"
                    ];
                    current-index: 0;
                    horizontal-stretch: 1;

                    init() => {
                        root.style_code = "castlevania-sotn";
                    }

                    selected(text) => {
                        if text == "Symphony of the Night" {
                            root.style_code = "castlevania-sotn";
                        } else if text == "Aria of Sorrow" {
                            root.style_code = "castlevania-aos";
                        } else if text == "Circle of the Moon" {
                            root.style_code = "castlevania-cotm";
                        } else if text == "Harmony of Dissonance" {
                            root.style_code = "castlevania-hod";
                        } else {
                            root.style_code = text;
                        }
                    }
                }
            }

            VerticalBox {
                alignment: end;
                spacing: 0.5rem;

                gen_button := Button {
                    colorize-icon: false;
                    text: "Generate map";
                    clicked => {
                        self.text = "Generating...";
                        self.enabled = false;

                        root.request-new-map(root.cols, root.rows, root.style_code);
                    }
                }

                save_button := Button {
                    text: "Save map";
                    vertical-stretch: 0;
                    enabled: false;
                    
                    clicked => {
                        self.text = "Saving...";
                        self.enabled = false;

                        root.request-save-map();
                    }
                }
            }
        }

        img := Image {
            width: parent.width - 20rem;
            height: parent.height - 1rem;
            image-fit: contain;

            source: root.map;
        }
    }
}
