name: Deploy Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'generator-lambda/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.87.0

      - name: Install cargo-lambda
        run: pip install cargo-lambda

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Lambda
        run: cargo lambda build --release --arm64 --manifest-path generator-lambda/Cargo.toml

      - name: Deploy Lambda
        run: cargo lambda deploy --manifest-path generator-lambda/Cargo.toml map-generator
